spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/citronix
    username: postgres
    password: post2001
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true